import {test,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';

test.describe.configure({mode:'serial'});
const ownerCode=process.env.MCB_TEST_OWNER_CODE||'adult-setup-code-0123456789';
const authToken=process.env.MCB_TEST_AUTH_TOKEN||'integration-test-entra-token';
const authenticate=async(page:import('@playwright/test').Page)=>page.addInitScript(token=>sessionStorage.setItem('mcb:test-access-token',token),authToken);

test('public gate uses only Sociobot Microsoft identity',async({page})=>{
  const consoleErrors:string[]=[];
  const origins=new Set<string>();
  page.on('console',message=>{if(message.type()==='error')consoleErrors.push(message.text())});
  page.on('pageerror',error=>consoleErrors.push(error.message));
  page.on('request',request=>origins.add(new URL(request.url()).origin));
  await page.goto('/');
  await page.keyboard.press('Tab');
  await expect(page.locator(':focus')).toHaveText('Skip to main content');
  await expect(page.getByRole('button',{name:'Sign in with Microsoft'})).toBeVisible();
  await expect(page.getByText(/sociobotcustomers\.ciamlogin\.com/)).toBeVisible();
  await expect(page.locator('input[type=password]')).toHaveCount(0);
  const results=await new AxeBuilder({page}).analyze();
  expect(results.violations.filter(v=>['serious','critical'].includes(v.impact||''))).toEqual([]);
  expect([...origins]).toEqual([new URL(page.url()).origin]);
  expect(consoleErrors).toEqual([]);
});

test('facilitator completes a session record and recap',async({page})=>{
  const consoleErrors:string[]=[];
  page.on('console',message=>{if(message.type()==='error')consoleErrors.push(message.text())});
  page.on('pageerror',error=>consoleErrors.push(error.message));
  await authenticate(page);
  await page.goto('/');
  await page.keyboard.press('Tab');
  await expect(page.locator(':focus')).toHaveText('Skip to main content');
  await expect.poll(()=>page.locator('.gate-art img').evaluate((img:HTMLImageElement)=>img.naturalWidth)).toBeGreaterThan(0);
  await expect(page.getByRole('heading',{level:1})).toHaveText('Follow every line of thinking.');
  await page.getByLabel('Facilitator name').fill('Morgan');
  await page.getByLabel('Circle name').fill('Saturday Circle');
  await page.getByLabel('Adult setup code').fill(ownerCode);
  await page.getByLabel(/I confirm that I am an adult/).check();
  await page.getByRole('button',{name:'Create private board'}).click();
  await expect(page.getByText('Plan the first gathering')).toBeVisible();
  await page.getByRole('button',{name:'New session'}).click();
  await page.getByLabel('Session title').fill('Parity paths');
  await page.getByLabel('Guiding focus').fill('What never changes?');
  await page.getByRole('button',{name:'Add session'}).click();
  await expect(page.getByText('The path through this session')).toBeVisible();
  await page.getByRole('button',{name:'Add problem'}).click();
  await page.getByLabel('Short title').fill('The coin trail');
  await page.getByLabel('Open prompt').fill('Move one coin at a time. Which arrangements can you reach?');
  await page.getByRole('button',{name:'Add to sequence'}).click();
  await page.getByRole('link',{name:'Learners'}).click();
  await page.getByLabel('Learner alias').fill('Ada');
  await page.getByRole('button',{name:'Add learner'}).click();
  await page.getByRole('link',{name:'Board',exact:true}).click();
  await page.getByLabel('What they tried').fill('Marked odd gaps and tested the smallest row first.');
  await page.locator('.status-option').filter({hasText:'Exploring'}).click();
  await page.getByPlaceholder('e.g. draw a diagram').fill('Test a smaller case');
  await page.getByRole('button',{name:'Add strategy'}).click();
  await page.getByRole('button',{name:'Save attempt'}).click();
  await expect(page.getByText('Attempt saved.')).toBeVisible();
  await page.getByLabel('Add photo').setInputFiles('frontend/public/art/lantern-room-768.webp');
  await expect(page.getByRole('img',{name:/Uploaded attempt/})).toBeVisible();
  const exported=await page.evaluate(async token=>{const response=await fetch('/api/export',{headers:{Authorization:`Bearer ${token}`}});return{ok:response.ok,data:await response.json()}},authToken);
  expect(exported.ok).toBeTruthy();
  expect(exported.data.attachment_files).toHaveLength(1);
  await page.getByRole('button',{name:'Print recap'}).click();
  await expect(page.getByText('Marked odd gaps and tested the smallest row first.')).toBeVisible();
  const results=await new AxeBuilder({page}).analyze();
  expect(results.violations.filter(v=>['serious','critical'].includes(v.impact||''))).toEqual([]);
  expect(consoleErrors).toEqual([]);
});

test('legal pages and mobile sign-in remain usable',async({browser})=>{
  const context=await browser.newContext({viewport:{width:390,height:844}});
  const page=await context.newPage();
  await authenticate(page);
  await page.goto('/privacy');
  await expect(page.getByRole('heading',{level:1})).toHaveText('A small record, kept private.');
  await page.goto('/');
  await expect(page.getByRole('link',{name:'Learners'})).toBeVisible();
  await expect(page.locator('input[type=password]')).toHaveCount(0);
  await expect(page.locator('body')).toHaveJSProperty('scrollWidth',390);
  const results=await new AxeBuilder({page}).analyze();
  expect(results.violations.filter(v=>['serious','critical'].includes(v.impact||''))).toEqual([]);
  await context.close();
});

test('an authenticated offline mobile reload restores the cached board and drafts',async({browser})=>{
  const context=await browser.newContext({viewport:{width:390,height:844}});
  const page=await context.newPage();
  await authenticate(page);
  await page.goto('/');
  await expect(page.getByRole('link',{name:'Learners'})).toBeVisible();
  await page.evaluate(()=>navigator.serviceWorker.ready.then(()=>true));
  await page.reload();
  await expect.poll(()=>page.evaluate(()=>navigator.serviceWorker.controller!==null)).toBe(true);
  await context.setOffline(true);
  await page.reload();
  await expect(page.getByRole('heading',{level:1})).toHaveText('Saturday Circle facilitator board');
  await expect(page.getByText(/Offline copy open/)).toBeVisible();
  await expect(page.locator('body')).toHaveJSProperty('scrollWidth',390);
  await context.close();
});
