import './style.css';
import {api,apiBlob,ApiFailure,send} from './api';
import {authority,signIn,signOut} from './auth';
import {clearDemo,isDemoMode,resetDemo} from './demo';
import type {Attempt,Board,CircleSession,Learner,Problem,Status} from './types';
import {escapeHtml,parseStrategies,shortDate,statusLabel} from './types';

const app=document.querySelector<HTMLDivElement>('#app')!;
let board:Board|null=null;
let selectedSession=0,selectedProblem=0,selectedLearner=0;
let view:'board'|'learners'|'recap'|'plus'|'settings'='board';
let notice='';
let online=navigator.onLine;
const offlineBoardKey='math-circle-board:offline-board';
const strategyPrompts=['Try a smaller case','Draw a diagram','Work backwards','Look for an invariant'];
const appPaths=new Set(['/board','/learners','/recap','/plus','/settings']);

function toast(message:string){notice=message;renderNotice();window.setTimeout(()=>{if(notice===message){notice='';renderNotice()}},3200)}
function renderNotice(){let region=document.querySelector<HTMLElement>('#notice');if(region)region.innerHTML=notice?`<div class="toast">${escapeHtml(notice)}</div>`:''}
function today(){return new Date().toISOString().slice(0,10)}
function setPageMeta(title:string,description:string,path=location.pathname){
  document.title=title;
  document.querySelector<HTMLMetaElement>('meta[name="description"]')?.setAttribute('content',description);
  document.querySelector<HTMLMetaElement>('meta[property="og:title"]')?.setAttribute('content',title);
  document.querySelector<HTMLMetaElement>('meta[property="og:description"]')?.setAttribute('content',description);
  document.querySelector<HTMLMetaElement>('meta[name="twitter:title"]')?.setAttribute('content',title);
  document.querySelector<HTMLMetaElement>('meta[name="twitter:description"]')?.setAttribute('content',description);
  const canonical=isDemoMode()?'/demo':path;
  document.querySelector<HTMLLinkElement>('link[rel="canonical"]')?.setAttribute('href',`https://math-circle-board.sociobot.in${canonical}`);
}
function demoQuery(){return isDemoMode()?'?demo=1':''}
function routeFor(next:typeof view){return `/${next}${demoQuery()}`}
function viewFromPath():typeof view{return appPaths.has(location.pathname)?location.pathname.slice(1) as typeof view:'board'}
function focusRoute(){requestAnimationFrame(()=>document.querySelector<HTMLElement>('main h1')?.focus())}

async function boot(){
  if(location.pathname==='/demo')history.replaceState({},'',`/?demo=1`);
  if(location.pathname==='/privacy'||location.pathname==='/terms'){renderLegal(location.pathname);return}
  if(location.pathname!=='/'&&location.pathname!=='/auth/callback'&&!appPaths.has(location.pathname)){renderNotFound();return}
  if(isDemoMode()){await loadBoard();return}
  try{const status=await api<Status>('/status');status.authenticated?await loadBoard():renderGate(status)}catch(error){if(!navigator.onLine){if(!restoreOfflineBoard())renderConnectionError();return}if(error instanceof ApiFailure&&error.status===401)renderGate({configured:true,signed_in:false,authenticated:false});else renderConnectionError()}
}

function renderGate(status:Status){
  const description='Plan open problems, record learner attempts, keep private notes, and print recaps for a small math circle.';
  setPageMeta('Math Circle Board — Plan small math-circle sessions',description,'/');
  app.innerHTML=`<header class="public-header"><a class="wordmark" href="/" aria-label="Math Circle Board home"><span class="mark">∴</span> Math Circle Board</a><nav aria-label="Public navigation"><a href="/demo">Demo</a><a href="#preview">Product preview</a><a href="#how-it-works">How it works</a><a href="/privacy">Privacy</a></nav></header>
  <main id="main" class="landing" tabindex="-1">
    <section class="landing-hero">
      <div class="gate-copy"><p class="eyebrow">For volunteer math circle facilitators</p><h1>Plan and record small math-circle sessions</h1><p class="lede">Sequence open problems, record partial attempts, keep private notes, and print a recap for 6–12 learners.</p>
        <div class="landing-actions"><a class="primary button-link" href="/demo">Try it with sample data</a><span>See a filled board. Changes stay in this demo.</span></div>
        ${status.signed_in&&!status.configured?`<form id="gate-form" class="gate-form"><p class="identity-note">Signed in with Microsoft. Finish the adult ownership check.</p><label>Facilitator name<input name="facilitator" autocomplete="name" maxlength="80" required></label><label>Circle name<input name="group_name" maxlength="100" value="Saturday problem circle" required></label><label>Adult setup code<input name="owner_code" autocomplete="off" minlength="24" required><small>The deployment operator gives this code to the responsible adult.</small></label><label class="adult-confirmation"><input name="adult_confirmed" type="checkbox" required> I am an adult responsible for this private group and will use learner aliases.</label><p id="form-error" class="form-error" role="alert"></p><button class="primary" type="submit">Create private board</button></form>`:`<div class="sign-in-row"><button id="entra-sign-in" class="secondary" type="button">Sign in with Microsoft</button><span>${status.configured?'Open the board owned by your account.':'Set up a board with the adult owner code.'}</span></div>`}
        <ul class="plain-facts"><li>Private boards require the owner’s Microsoft sign-in.</li><li>Sample mode reloads offline after its first visit.</li><li>All current board tools are free.</li></ul>
      </div>
      <figure class="gate-art"><picture><source type="image/webp" srcset="/art/lantern-room-768.webp 768w, /art/lantern-room-1536.webp 1536w" sizes="(max-width: 900px) 100vw, 56vw"><img src="/art/lantern-room-1536.webp" width="1536" height="1024" alt="An empty mathematics workshop with problem cards beneath a desk lamp" fetchpriority="high" decoding="async"></picture><figcaption>Sample problem cards on a facilitator’s table.</figcaption></figure>
    </section>
    <section id="preview" class="public-section preview-section" aria-labelledby="preview-title"><div><p class="eyebrow">Product preview</p><h2 id="preview-title">See one session at a glance</h2><p>The board keeps the problem order, learner status, and next discussion prompt together.</p><a href="/demo">Open this sample board</a></div><div class="preview-board" aria-label="Sample session preview"><span>Invariants in motion · Aug 29</span><ol><li><strong>01 The coin trail</strong><small>2 of 3 attempts recorded</small></li><li><strong>02 Corner cuts</strong><small>1 of 3 attempts recorded</small></li><li><strong>03 Switching lamps</strong><small>No attempts yet</small></li></ol></div></section>
    <section id="how-it-works" class="public-section steps-section" aria-labelledby="steps-title"><p class="eyebrow">How it works</p><h2 id="steps-title">Run the session in three steps</h2><ol><li><strong>Sequence problems</strong><span>Add prompts in the order you plan to discuss them.</span></li><li><strong>Record attempts</strong><span>Save partial ideas, strategy tags, and a private facilitator note.</span></li><li><strong>Print the recap</strong><span>Make a session record that leaves private notes out.</span></li></ol></section>
    <section class="public-section limits-section" aria-labelledby="privacy-title"><div><p class="eyebrow">Privacy and limits</p><h2 id="privacy-title">Keep only the record you need</h2><p>Use aliases instead of learner emails. The board is not a gradebook, chat service, or public learner profile.</p><a href="/privacy">Read the privacy details</a></div><div><p class="eyebrow">Release scope</p><h2>This release is for one private circle</h2><p>It has no paid plan, checkout, organization controls, or extra storage tier.</p><a href="/demo">Use four free strategy prompts</a></div></section>
  </main>${publicFooter()}`;
  document.querySelector('#entra-sign-in')?.addEventListener('click',()=>signIn());
  document.querySelector<HTMLFormElement>('#gate-form')?.addEventListener('submit',async e=>{
    e.preventDefault();const formElement=e.currentTarget as HTMLFormElement;const form=new FormData(formElement);const button=formElement.querySelector<HTMLButtonElement>('button')!;button.disabled=true;button.textContent='Creating…';
    const data:Record<string,unknown>=Object.fromEntries(form);data.adult_confirmed=form.get('adult_confirmed')==='on';
    try{await send('/setup',data);await loadBoard()}catch(err){showFormError(err)}finally{button.disabled=false;button.textContent='Create private board'}
  });
}

async function loadBoard(){
  try{board=await api<Board>('/board');rememberBoard();selectBoardDefaults();view=viewFromPath();if(location.pathname==='/'||location.pathname==='/auth/callback')history.replaceState({},'',routeFor(view));renderApp()}catch(err){if(!navigator.onLine){if(!restoreOfflineBoard())renderConnectionError();return}if(err instanceof ApiFailure&&(err.status===401||err.status===403))renderGate({configured:true,signed_in:err.status===403,authenticated:false});else renderConnectionError()}
}
function selectBoardDefaults(){if(!board)return;selectedSession=selectedSession&&board.sessions.some(s=>s.id===selectedSession)?selectedSession:board.sessions[0]?.id||0;selectedProblem=selectedProblem&&board.problems.some(p=>p.id===selectedProblem)?selectedProblem:board.problems.find(p=>p.session_id===selectedSession)?.id||0;selectedLearner=selectedLearner&&board.learners.some(l=>l.id===selectedLearner)?selectedLearner:board.learners[0]?.id||0}
function rememberBoard(){if(board&&!isDemoMode())localStorage.setItem(offlineBoardKey,JSON.stringify(board))}
function restoreOfflineBoard(){try{const cached=localStorage.getItem(offlineBoardKey);if(!cached)return false;board=JSON.parse(cached) as Board;online=false;selectBoardDefaults();renderApp();toast('Offline copy open. You can review records and keep drafts on this device.');return true}catch{return false}}

function renderApp(){if(!board)return;const pageName={board:'Board',learners:'Learners',recap:'Session recap',plus:'Strategy prompts',settings:'Settings'}[view];const title=isDemoMode()?`${view==='board'?'Demo':`Demo ${pageName.toLowerCase()}`} — Math Circle Board`:`${pageName} — Math Circle Board`;setPageMeta(title,`Plan and record sessions for ${board.group_name}.`,location.pathname);app.innerHTML=`<div class="shell ${isDemoMode()?'demo-shell':''}">
  ${isDemoMode()?'<aside class="demo-banner" aria-label="Demo controls"><strong>Demo — sample data, nothing is saved</strong><span>Changes stay in this browser tab.</span><button id="reset-demo" type="button">Reset demo</button><a href="/" id="leave-demo">Start for real</a></aside>':''}
  <header class="topbar"><a class="brand" href="${routeFor('board')}" data-view="board"><span class="mark">∴</span><span><small>Math Circle Board</small><strong>${escapeHtml(board.group_name)}</strong></span></a>
    <nav aria-label="Main navigation"><a href="${routeFor('board')}" data-view="board" ${view==='board'?'aria-current="page"':''}>Board</a><a href="${routeFor('learners')}" data-view="learners" ${view==='learners'?'aria-current="page"':''}>Learners</a><a href="${routeFor('plus')}" data-view="plus" ${view==='plus'?'aria-current="page"':''}>Strategies</a><a href="${routeFor('settings')}" data-view="settings" ${view==='settings'?'aria-current="page"':''}>Settings</a></nav>
  </header>
  <main id="main" class="workspace" tabindex="-1"><h1 class="sr-only" tabindex="-1">${escapeHtml(pageName)} for ${escapeHtml(board.group_name)}</h1>${renderView()}</main>
  <div class="sr-only" aria-live="polite">${escapeHtml(pageName)} page</div>
  <div id="notice" class="notice" aria-live="polite"></div>
  <footer class="app-footer"><span>${isDemoMode()?'Sample changes stay in this browser tab.':'Private board data stays on this product server.'}</span><span><a href="/privacy">Privacy</a> · <a href="/terms">Terms</a> · Built by Param Factory · v0.1.0</span></footer>
  ${online?'':'<div class="offline" role="status">You’re offline. Your writing stays in this browser; reconnect before saving.</div>'}
  </div>`;bindCommon();bindView();loadPrivateImages();renderNotice()}

function renderView(){switch(view){case'learners':return renderLearners();case'recap':return renderRecap();case'plus':return renderPlus();case'settings':return renderSettings();default:return renderBoard()}}
function session():CircleSession|undefined{return board?.sessions.find(s=>s.id===selectedSession)}
function problem():Problem|undefined{return board?.problems.find(p=>p.id===selectedProblem)}
function learner():Learner|undefined{return board?.learners.find(l=>l.id===selectedLearner)}
function attempt():Attempt|undefined{return board?.attempts.find(a=>a.learner_id===selectedLearner&&a.problem_id===selectedProblem)}

function renderBoard(){if(!board)return'';const current=session();return`<section class="board-head"><div><p class="eyebrow">Session plan</p><h2>${current?escapeHtml(current.title):'Plan the first gathering'}</h2>${current?`<p>${shortDate(current.session_date)}${current.focus?` · ${escapeHtml(current.focus)}`:''}</p>`:'<p>Start with a date and one guiding question.</p>'}</div><div class="head-actions"><label class="select-label">Session<select id="session-select">${board.sessions.map(s=>`<option value="${s.id}" ${s.id===selectedSession?'selected':''}>${escapeHtml(s.title)} · ${shortDate(s.session_date)}</option>`).join('')}</select></label>${current?'<button id="recap-button" class="secondary">Print recap</button>':''}<button id="toggle-session" class="primary">New session</button></div></section>
  <section id="session-form-wrap" class="reveal" hidden><form id="session-form" class="inline-form"><div><h3>New session</h3><p>Give this gathering a clear place in the sequence.</p></div><label>Session title<input name="title" required maxlength="100" placeholder="Invariants in motion"></label><label>Date<input name="session_date" type="date" required value="${today()}"></label><label>Guiding focus<input name="focus" maxlength="300" placeholder="What stays unchanged?"></label><button class="primary" type="submit">Add session</button><p class="form-error" role="alert"></p></form></section>
  ${current?renderSession(current):renderFirstSession()}`}

function renderFirstSession(){return`<section class="empty-state"><div class="empty-orbit" aria-hidden="true">①</div><h2>No sessions yet</h2><p>Create a session, then add two or three open problems.</p><button class="primary" data-open-session>Create the first session</button></section>`}
function renderSession(current:CircleSession){if(!board)return'';const problems=board.problems.filter(p=>p.session_id===current.id);return`<section class="trail-section" aria-labelledby="trail-title"><div class="section-title"><div><p class="eyebrow">Problem sequence</p><h3 id="trail-title">Problems in this session</h3></div><button id="toggle-problem" class="secondary">Add problem</button></div>
  <div id="problem-form-wrap" class="reveal" hidden><form id="problem-form" class="inline-form problem-form"><label>Short title<input name="title" required maxlength="120" placeholder="The disappearing corners"></label><label>Open prompt<textarea name="prompt" required maxlength="2000" rows="3" placeholder="A rectangle has its corners cut away… What do you notice?"></textarea></label><button class="primary" type="submit">Add to sequence</button><p class="form-error" role="alert"></p></form></div>
  ${problems.length?`<ol class="problem-trail">${problems.map((p,i)=>`<li><button class="problem-card ${p.id===selectedProblem?'selected':''}" data-problem="${p.id}" aria-pressed="${p.id===selectedProblem}"><span class="problem-number">${String(i+1).padStart(2,'0')}</span><span><strong>${escapeHtml(p.title)}</strong><small>${escapeHtml(p.prompt)}</small></span><span class="trail-status">${attemptProgress(p.id)}</span></button></li>`).join('')}</ol>`:`<div class="inline-empty"><span aria-hidden="true">↝</span><p><strong>No problems yet.</strong><br>Add an open prompt to begin.</p></div>`}
  </section>${problems.length?renderWorkbench():''}`}
function attemptProgress(problemId:number){if(!board)return'';const items=board.attempts.filter(a=>a.problem_id===problemId);return `${items.filter(a=>a.status==='shared').length}/${board.learners.length} shared`}

function renderWorkbench(){if(!board)return'';const p=problem();if(!p)return'';if(!board.learners.length)return`<section class="workbench empty-workbench"><div><p class="eyebrow">Attempt workbench</p><h3>Add a learner to record thinking</h3><p>Aliases or first names are enough. Avoid emails and identifying details.</p></div><button class="primary" data-view="learners">Add learners</button></section>`;const a=attempt();const strategies=a?parseStrategies(a.strategies):[];const attachments=a?board.attachments.filter(x=>x.attempt_id===a.id):[];return`<section class="workbench" aria-labelledby="workbench-title"><div class="workbench-heading"><div><p class="eyebrow">Attempt workbench</p><h3 id="workbench-title">${escapeHtml(p.title)}</h3></div><label class="select-label">Learner<select id="learner-select">${board.learners.map(l=>`<option value="${l.id}" ${l.id===selectedLearner?'selected':''}>${escapeHtml(l.alias)}</option>`).join('')}</select></label></div>
  <p class="problem-prompt">${escapeHtml(p.prompt)}</p><form id="attempt-form" class="attempt-form"><div class="status-row"><span id="status-label">Where are they now?</span>${(['not_started','exploring','shared'] as const).map(s=>`<label class="status-option"><input type="radio" name="status" value="${s}" ${(a?.status||'not_started')===s?'checked':''}><span>${statusLabel(s)}</span></label>`).join('')}</div>
  <label>What they tried<textarea name="thinking" rows="5" maxlength="5000" placeholder="Capture the partial idea, diagram, conjecture, or useful wrong turn…">${escapeHtml(a?.thinking||draftValue('thinking'))}</textarea></label>
  <fieldset class="strategies"><legend>Strategies tried</legend><div id="strategy-chips">${strategies.map(s=>chip(s)).join('')}</div><div class="add-strategy"><label class="sr-only" for="strategy-input">Add a strategy</label><input id="strategy-input" maxlength="40" placeholder="e.g. draw a diagram"><button type="button" id="add-strategy" class="secondary">Add strategy</button></div><div class="preset-row" aria-label="Strategy prompt palette">${strategyPrompts.map(s=>`<button type="button" class="preset" data-preset="${s}">+ ${s}</button>`).join('')}</div></fieldset>
  <label class="private-note"><span><strong>Private facilitator note</strong><small>Never shown in the printable learner recap.</small></span><textarea name="private_note" rows="3" maxlength="3000" placeholder="A prompt to try next time…">${escapeHtml(a?.private_note||draftValue('private_note'))}</textarea></label>
  <div class="save-row"><button class="primary" type="submit">Save attempt</button><span id="save-state" role="status">${a?`Last saved ${new Date(a.updated_at*1000).toLocaleString()}`:'Not saved yet'}</span></div></form>
  <section class="evidence" aria-labelledby="evidence-title"><div><h4 id="evidence-title">Photo evidence</h4><p>Private images of paper work only. JPEG, PNG, or WebP under 5 MB.</p></div>${a?`<label class="upload-button">Add photo<input id="photo-input" type="file" accept="image/jpeg,image/png,image/webp"></label>`:'<small>Save the attempt before adding a photo.</small>'}<div class="photo-grid">${attachments.map(x=>`<figure><img data-private-image="${x.id}" alt="Uploaded attempt: ${escapeHtml(x.original_name)}" loading="lazy" width="220" height="160"><figcaption>${escapeHtml(x.original_name)} <button class="text-danger" data-delete-file="${x.id}">Remove</button></figcaption></figure>`).join('')}</div></section>
  </section>`}
function chip(value:string){return`<span class="chip" data-value="${escapeHtml(value)}">${escapeHtml(value)}<button type="button" aria-label="Remove strategy ${escapeHtml(value)}">×</button></span>`}
function draftKey(){return`${isDemoMode()?'demo:math-circle-board:':'mcb-'}draft:${selectedLearner}:${selectedProblem}`}
function draftStorage(){return isDemoMode()?sessionStorage:localStorage}
function draftValue(key:string){try{return JSON.parse(draftStorage().getItem(draftKey())||'{}')[key]||''}catch{return''}}

function renderLearners(){if(!board)return'';return`<section class="page-section narrow"><div class="board-head"><div><p class="eyebrow">Private roster</p><h2>Learners</h2><p>Use a first name or alias. No email address is needed.</p></div><span class="count">${board.learners.length} learner${board.learners.length===1?'':'s'}</span></div><form id="learner-form" class="add-learner"><label>Learner alias<input name="alias" required maxlength="60" placeholder="Ada"></label><button class="primary" type="submit">Add learner</button><p class="form-error" role="alert"></p></form>${board.learners.length?`<ul class="learner-list">${board.learners.map(l=>`<li><span class="avatar" aria-hidden="true">${escapeHtml(l.alias[0]?.toUpperCase()||'?')}</span><span><strong>${escapeHtml(l.alias)}</strong><small>${board!.attempts.filter(a=>a.learner_id===l.id).length} recorded attempts</small></span><button class="text-danger" data-delete-learner="${l.id}" data-name="${escapeHtml(l.alias)}">Remove</button></li>`).join('')}</ul>`:`<div class="empty-state compact"><h3>No learner records yet</h3><p>Add aliases when you are ready to capture attempts.</p></div>`}</section>`}

function renderRecap(){if(!board)return'';const s=session();if(!s)return'';const problems=board.problems.filter(p=>p.session_id===s.id);return`<section class="recap"><div class="no-print recap-toolbar"><button class="secondary" data-view="board">← Back to board</button><div><button id="print" class="primary">Print session recap</button></div></div><header class="recap-title"><p>Math Circle Board · Session recap</p><h2>${escapeHtml(board.group_name)}</h2><div><strong>${escapeHtml(s.title)}</strong><span>${shortDate(s.session_date)}</span></div>${s.focus?`<p>Focus: ${escapeHtml(s.focus)}</p>`:''}</header>
  <section class="recap-summary"><div><span>${board.learners.length}</span> learners</div><div><span>${problems.length}</span> problems</div><div><span>${board.attempts.filter(a=>problems.some(p=>p.id===a.problem_id)&&a.status==='shared').length}</span> shared attempts</div></section>
  ${board.learners.map(l=>{const records=board!.attempts.filter(a=>a.learner_id===l.id&&problems.some(p=>p.id===a.problem_id)&&a.status!=='not_started');return`<section class="learner-recap"><h3>${escapeHtml(l.alias)}</h3>${records.length?`<ul>${records.map(a=>{const p=board!.problems.find(x=>x.id===a.problem_id)!;return`<li><div><strong>${escapeHtml(p.title)}</strong><span>${statusLabel(a.status)}</span></div>${a.thinking?`<p>${escapeHtml(a.thinking)}</p>`:''}${parseStrategies(a.strategies).length?`<small>Strategies: ${parseStrategies(a.strategies).map(escapeHtml).join(' · ')}</small>`:''}</li>`}).join('')}</ul>`:'<p class="muted">No attempt recorded this session.</p>'}</section>`}).join('')}<footer class="recap-footer">Private facilitator-generated record · ${new Date().toLocaleDateString()}</footer></section>`}

function renderPlus(){return`<section class="page-section plus-page"><div class="plus-hero"><p class="eyebrow">Strategy prompts</p><h2>Four strategy prompts are included</h2><p>Choose a prompt in any attempt workbench, then save it with the attempt.</p><p class="success">✓ Available in every private board and the sample.</p></div><div class="plus-details"><h3>Choose a starting move</h3><ul>${strategyPrompts.map(prompt=>`<li><span aria-hidden="true">↝</span><div><strong>${prompt}</strong><p>Add it to an attempt with one tap.</p></div></li>`).join('')}</ul><p class="fineprint">This release has no paid plan, checkout, organization controls, or extra storage tier. See <a href="/privacy">privacy</a> and <a href="/terms">terms</a>.</p></div></section>`}

function renderSettings(){if(!board)return'';return`<section class="page-section narrow"><p class="eyebrow">Data controls</p><h2>Settings and data</h2><div class="settings-list"><section><div><h3>Export all board data</h3><p>Download aliases, sessions, problems, attempts, and private notes as JSON.</p></div><button id="export-data" class="secondary">Export data</button></section>${isDemoMode()?'<section><div><h3>Reset sample data</h3><p>Restore the original sample sessions and attempts.</p></div><button id="settings-reset-demo" class="secondary">Reset demo</button></section>':'<section><div><h3>End this visit</h3><p>Sign out of Microsoft on this device. Circle records remain on the server.</p></div><button id="logout" class="secondary">Sign out</button></section>'}</div><section class="danger-zone"><h3>Delete sessions</h3><p>Delete one session and its attempts. This cannot be undone.</p>${board.sessions.map(s=>`<div><span>${escapeHtml(s.title)} · ${shortDate(s.session_date)}</span><button class="text-danger" data-delete-session="${s.id}" data-name="${escapeHtml(s.title)}">Delete session</button></div>`).join('')||'<p>No sessions to delete.</p>'}</section>${isDemoMode()?'':`<section class="danger-zone delete-board-zone"><h3>Delete the private board</h3><p>Delete every learner, session, attempt, note, and photo. This cannot be undone.</p><button id="delete-board" class="danger-button">Delete the entire board</button></section>`}</section>`}

function navigateToView(next:typeof view){view=next;history.pushState({view},'',routeFor(view));renderApp();focusRoute()}
function bindCommon(){document.querySelectorAll<HTMLElement>('[data-view]').forEach(el=>el.addEventListener('click',e=>{e.preventDefault();navigateToView(el.dataset.view as typeof view)}));document.querySelector('#reset-demo')?.addEventListener('click',()=>{resetDemo();selectedSession=0;selectedProblem=0;selectedLearner=0;loadBoard().then(()=>toast('Sample data reset.'))});document.querySelector('#leave-demo')?.addEventListener('click',()=>clearDemo());window.ononline=()=>{online=true;toast('Back online. You can save again.');renderApp()};window.onoffline=()=>{online=false;renderApp()}}
function bindView(){if(view==='board')bindBoard();if(view==='learners')bindLearners();if(view==='recap')document.querySelector('#print')?.addEventListener('click',()=>window.print());if(view==='settings')bindSettings()}
function toggle(id:string,show?:boolean){const el=document.querySelector<HTMLElement>(id);if(el){el.hidden=show===undefined?!el.hidden:!show;if(!el.hidden)el.querySelector<HTMLElement>('input,textarea')?.focus()}}
function bindBoard(){
  document.querySelector('#toggle-session')?.addEventListener('click',()=>toggle('#session-form-wrap'));document.querySelector('[data-open-session]')?.addEventListener('click',()=>toggle('#session-form-wrap',true));document.querySelector('#toggle-problem')?.addEventListener('click',()=>toggle('#problem-form-wrap'));
  document.querySelector<HTMLSelectElement>('#session-select')?.addEventListener('change',e=>{selectedSession=Number((e.currentTarget as HTMLSelectElement).value);selectedProblem=board?.problems.find(p=>p.session_id===selectedSession)?.id||0;renderApp()});document.querySelectorAll<HTMLElement>('[data-problem]').forEach(x=>x.addEventListener('click',()=>{selectedProblem=Number(x.dataset.problem);renderApp()}));document.querySelector<HTMLSelectElement>('#learner-select')?.addEventListener('change',e=>{selectedLearner=Number((e.currentTarget as HTMLSelectElement).value);renderApp()});document.querySelector('#recap-button')?.addEventListener('click',()=>navigateToView('recap'));
  bindJsonForm('#session-form','/sessions',()=>loadBoard());bindJsonForm('#problem-form','/problems',()=>loadBoard(),()=>({session_id:selectedSession}));
  const form=document.querySelector<HTMLFormElement>('#attempt-form');if(form){const saveDraft=()=>{const fd=new FormData(form);draftStorage().setItem(draftKey(),JSON.stringify({thinking:fd.get('thinking'),private_note:fd.get('private_note')}))};form.querySelectorAll('textarea').forEach(t=>t.addEventListener('input',saveDraft));form.addEventListener('submit',saveAttempt);document.querySelector('#add-strategy')?.addEventListener('click',()=>addStrategy());document.querySelector('#strategy-input')?.addEventListener('keydown',e=>{if((e as KeyboardEvent).key==='Enter'){e.preventDefault();addStrategy()}});document.querySelectorAll<HTMLElement>('[data-preset]').forEach(x=>x.addEventListener('click',()=>addStrategy(x.dataset.preset)));bindChipRemoval()}
  document.querySelector<HTMLInputElement>('#photo-input')?.addEventListener('change',uploadPhoto);document.querySelectorAll<HTMLElement>('[data-delete-file]').forEach(x=>x.addEventListener('click',()=>deletePhoto(Number(x.dataset.deleteFile))));
}
function bindJsonForm(selector:string,path:string,done:()=>void,extra=()=>({})){const form=document.querySelector<HTMLFormElement>(selector);form?.addEventListener('submit',async e=>{e.preventDefault();const button=form.querySelector<HTMLButtonElement>('button[type=submit]')!;button.disabled=true;try{await send(path,{...Object.fromEntries(new FormData(form)),...extra()});toast('Saved to the board.');done()}catch(err){showFormError(err,form)}finally{button.disabled=false}})}
function strategies(){return [...document.querySelectorAll<HTMLElement>('#strategy-chips .chip')].map(x=>x.dataset.value||'')}
function addStrategy(preset?:string){const input=document.querySelector<HTMLInputElement>('#strategy-input')!;const value=(preset||input.value).trim();if(!value||strategies().some(s=>s.toLowerCase()===value.toLowerCase()))return;const wrap=document.querySelector('#strategy-chips')!;wrap.insertAdjacentHTML('beforeend',chip(value));input.value='';bindChipRemoval();input.focus()}
function bindChipRemoval(){document.querySelectorAll<HTMLButtonElement>('.chip button').forEach(b=>{b.onclick=()=>b.parentElement?.remove()})}
async function saveAttempt(e:SubmitEvent){e.preventDefault();if(!online&&!isDemoMode()){toast('You’re offline. Draft kept on this device.');return}const form=e.currentTarget as HTMLFormElement;const button=form.querySelector<HTMLButtonElement>('button[type=submit]')!;button.disabled=true;document.querySelector('#save-state')!.textContent='Saving…';try{await send('/attempts',{...Object.fromEntries(new FormData(form)),learner_id:selectedLearner,problem_id:selectedProblem,strategies:strategies()});draftStorage().removeItem(draftKey());toast('Attempt saved.');await loadBoard()}catch(err){document.querySelector('#save-state')!.textContent=messageOf(err)}finally{button.disabled=false}}
async function uploadPhoto(e:Event){const input=e.currentTarget as HTMLInputElement;const file=input.files?.[0],a=attempt();if(!file||!a)return;const data=new FormData();data.append('image',file);try{await api(`/attempts/${a.id}/upload`,{method:'POST',body:data});toast('Photo added privately.');await loadBoard()}catch(err){toast(messageOf(err))}}
async function deletePhoto(id:number){if(!confirm('Remove this attempt photo? This cannot be undone.'))return;try{await api(`/files/${id}`,{method:'DELETE'});toast('Photo removed.');await loadBoard()}catch(err){toast(messageOf(err))}}
async function loadPrivateImages(){for(const image of document.querySelectorAll<HTMLImageElement>('[data-private-image]')){try{const blob=await apiBlob(`/files/${image.dataset.privateImage}`);const url=URL.createObjectURL(blob);image.src=url;image.addEventListener('load',()=>URL.revokeObjectURL(url),{once:true})}catch{image.alt='Private attempt image unavailable'}}}
async function exportData(){try{const blob=await apiBlob('/export');const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download='math-circle-board-export.json';link.click();URL.revokeObjectURL(url);toast('Export downloaded.')}catch(err){toast(messageOf(err))}}
function bindLearners(){bindJsonForm('#learner-form','/learners',()=>loadBoard());document.querySelectorAll<HTMLElement>('[data-delete-learner]').forEach(x=>x.addEventListener('click',async()=>{if(!confirm(`Remove ${x.dataset.name} and all of their attempts? This cannot be undone.`))return;try{await api(`/learners/${x.dataset.deleteLearner}`,{method:'DELETE'});toast('Learner record removed.');await loadBoard()}catch(err){toast(messageOf(err))}}))}
function bindSettings(){document.querySelector('#export-data')?.addEventListener('click',exportData);document.querySelector('#settings-reset-demo')?.addEventListener('click',()=>{resetDemo();selectedSession=0;selectedProblem=0;selectedLearner=0;loadBoard().then(()=>toast('Sample data reset.'))});document.querySelector('#logout')?.addEventListener('click',async()=>{board=null;localStorage.removeItem(offlineBoardKey);await signOut()});document.querySelector('#delete-board')?.addEventListener('click',async()=>{if(!confirm(`Delete the entire “${board?.group_name}” board, including every learner, note, and photo? This cannot be undone.`))return;try{await api('/board',{method:'DELETE'});board=null;localStorage.removeItem(offlineBoardKey);location.assign('/')}catch(err){toast(messageOf(err))}});document.querySelectorAll<HTMLElement>('[data-delete-session]').forEach(x=>x.addEventListener('click',async()=>{if(!confirm(`Delete “${x.dataset.name}” and every attempt in it? This cannot be undone.`))return;try{await api(`/sessions/${x.dataset.deleteSession}`,{method:'DELETE'});selectedSession=0;toast('Session deleted.');await loadBoard()}catch(err){toast(messageOf(err))}}))}
function showFormError(error:unknown,form:ParentNode=document){const el=form.querySelector<HTMLElement>('.form-error');if(el)el.textContent=messageOf(error)}
function messageOf(error:unknown){return error instanceof Error?error.message:'Something went wrong. Try again.'}

function publicHeader(){return`<header class="public-header"><a class="wordmark" href="/"><span class="mark">∴</span> Math Circle Board</a><nav aria-label="Public navigation"><a href="/demo">Demo</a><a href="/privacy">Privacy</a><a href="/terms">Terms</a></nav></header>`}
function publicFooter(){return`<footer class="public-footer"><span>Plan and record small math-circle sessions.</span><a href="/privacy">Privacy</a><a href="/terms">Terms</a><span>Built by Param Factory</span><span>v0.1.0 · Original AI-assisted environmental art</span></footer>`}
function renderConnectionError(){setPageMeta('Connection problem — Math Circle Board','Math Circle Board could not reach its server.');app.innerHTML=`${publicHeader()}<main id="main" class="connection-error" tabindex="-1"><div class="mark" aria-hidden="true">∴</div><h1>Cannot reach the board</h1><p>Check your connection, then try again.</p><button id="retry-load" class="primary">Try again</button></main>${publicFooter()}`;document.querySelector('#retry-load')?.addEventListener('click',()=>location.reload())}
function renderLegal(path:string){const privacy=path==='/privacy';setPageMeta(`${privacy?'Privacy':'Terms'} — Math Circle Board`,privacy?'How Math Circle Board stores, uses, exports, and deletes facilitator data.':'Terms for using Math Circle Board.',path);app.innerHTML=`${publicHeader()}<main id="main" class="legal" tabindex="-1"><p class="eyebrow">${privacy?'Privacy':'Terms'}</p><h1>${privacy?'How Math Circle Board handles data':'Terms of use'}</h1>${privacy?`<p>Math Circle Board stores facilitator names, circle names, learner aliases, session plans, attempts, private notes, strategy tags, and uploaded images.</p><p>It does not require learner emails. It does not run ads, analytics, or behavioral tracking.</p><p>Microsoft handles the adult sign-in. The board stores the account identifier, not the account password.</p><h2>Where data lives</h2><p>Board data and images live in this product’s SQLite database and upload directory.</p><p>The last opened board and unsaved drafts may stay in this browser for offline use. Signing out clears the cached board.</p><p>Sample mode uses a separate <code>demo:</code> session-storage namespace. It never opens the private board API.</p><h2>Your controls</h2><p>Facilitators can export all board data, remove photos and learners, delete sessions, or delete the entire private board.</p><p>Use aliases and avoid details that are not needed for the math circle.</p><h2>Release scope</h2><p>This release has no paid plan, checkout, organization controls, or extra storage tier.</p>`:`<p>Math Circle Board records sessions for adult-run enrichment groups. The adult facilitator is responsible for consent and appropriate use.</p><h2>Acceptable use</h2><p>Do not use this service for grades, emergency records, public child profiles, illegal material, or rights-infringing content.</p><p>Protect access to the Microsoft account that owns the board.</p><h2>Release scope</h2><p>This release has no paid plan, checkout, organization controls, or extra storage tier.</p><p>Four strategy prompts are included in every private board and the sample.</p><h2>Service limits</h2><p>The service may be interrupted. Export important records regularly.</p><p>Liability is limited to the amount paid where the law allows.</p>`}<p class="legal-date">Effective 2 September 2026 · Contact the operator through sociobot.in for privacy or support requests.</p><a class="secondary button-link" href="/">Return home</a></main>${publicFooter()}`}
function renderNotFound(){setPageMeta('Page not found — Math Circle Board','Return to Math Circle Board and open a valid page.',location.pathname);app.innerHTML=`${publicHeader()}<main id="main" class="not-found" tabindex="-1"><div class="not-found-mark" aria-hidden="true">404</div><h1>This page does not exist</h1><p>Return home or open the sample board.</p><div><a class="primary button-link" href="/">Return home</a><a class="secondary button-link" href="/demo">Try sample data</a></div></main>${publicFooter()}`}

boot();
window.addEventListener('popstate',()=>{if(board&&appPaths.has(location.pathname)){view=viewFromPath();renderApp();focusRoute()}else boot()});
document.querySelector<HTMLAnchorElement>('.skip-link')?.addEventListener('click',event=>{event.preventDefault();history.replaceState(history.state,'',`${location.pathname}${location.search}#main`);document.querySelector<HTMLElement>('#main')?.focus()});
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('/sw.js').catch(()=>{}));
