import './style.css';
import {api,apiBlob,ApiFailure,send} from './api';
import {authority,signIn,signOut} from './auth';
import type {Attempt,Board,CircleSession,Learner,Problem,Status} from './types';
import {escapeHtml,parseStrategies,shortDate,statusLabel} from './types';

const app=document.querySelector<HTMLDivElement>('#app')!;
let board:Board|null=null;
let selectedSession=0,selectedProblem=0,selectedLearner=0;
let view:'board'|'learners'|'recap'|'plus'|'settings'='board';
let notice='';
let online=navigator.onLine;
const slug='math-circle-board';
const billing='https://api.sociobot.in/api/v1';
const licenseKey=`sb_license:${slug}`;
const offlineBoardKey=`${slug}:offline-board`;
let plusUnlocked=false;

function toast(message:string){notice=message;renderNotice();window.setTimeout(()=>{if(notice===message){notice='';renderNotice()}},3200)}
function renderNotice(){let region=document.querySelector<HTMLElement>('#notice');if(region)region.innerHTML=notice?`<div class="toast">${escapeHtml(notice)}</div>`:''}
function today(){return new Date().toISOString().slice(0,10)}
function setTitle(suffix:string){document.title=`${suffix} — Math Circle Board`}

async function boot(){
  captureLicense();
  if(location.pathname==='/privacy'||location.pathname==='/terms'){renderLegal(location.pathname);return}
  try{const status=await api<Status>('/status');status.authenticated?await loadBoard():renderGate(status)}catch(error){if(!navigator.onLine){if(!restoreOfflineBoard())renderConnectionError();return}if(error instanceof ApiFailure&&error.status===401)renderGate({configured:true,signed_in:false,authenticated:false});else renderConnectionError()}
  verifyLicense();
}

function captureLicense(){const params=new URLSearchParams(location.search);const token=params.get('license');if(token){localStorage.setItem(licenseKey,token);params.delete('license');history.replaceState({},'',`${location.pathname}${params.size?`?${params}`:''}${location.hash}`)}}
async function verifyLicense(){
  const token=localStorage.getItem(licenseKey);if(!token)return;
  const cached=localStorage.getItem(`${licenseKey}:verdict`);if(cached){try{const v=JSON.parse(cached);if(Date.now()-v.checked<86400000){plusUnlocked=!!v.valid;if(board)renderApp();return}}catch{}}
  try{const res=await fetch(`${billing}/products/${slug}/verify?license=${encodeURIComponent(token)}`);const v=await res.json();localStorage.setItem(`${licenseKey}:verdict`,JSON.stringify({...v,checked:Date.now()}));plusUnlocked=!!v.valid;if(board)renderApp();if(!v.valid)toast('This Plus license is no longer active.')}catch{/* free board remains available offline */}
}

function renderGate(status:Status){
  setTitle(status.configured?'Private board':'Set up your private board');
  app.innerHTML=`<main id="main" class="gate">
    <section class="gate-copy">
      <a class="wordmark" href="/" aria-label="Math Circle Board home"><span class="mark">∴</span> Math Circle Board</a>
      <p class="eyebrow">A field notebook for shared discoveries</p>
      <h1>${status.configured?'Welcome back to the circle.':'Follow every line of thinking.'}</h1>
      <p class="lede">Sequence open-ended problems, catch partial strategies, and leave each gathering with a learning record worth keeping.</p>
      ${status.signed_in&&!status.configured?`<form id="gate-form" class="gate-form"><p class="identity-note">✓ Signed in with Microsoft Entra External ID. Finish the one-time adult ownership check.</p><label>Facilitator name<input name="facilitator" autocomplete="name" maxlength="80" required></label><label>Circle name<input name="group_name" maxlength="100" value="Saturday problem circle" required></label><label>Adult setup code<input name="owner_code" autocomplete="off" minlength="24" required><small>Issued privately by the deployment operator to the adult responsible for this group.</small></label><label class="adult-confirmation"><input name="adult_confirmed" type="checkbox" required> I confirm that I am an adult responsible for this private group and will use learner aliases.</label><p id="form-error" class="form-error" role="alert"></p><button class="primary" type="submit">Create private board</button></form>`:`<div class="gate-form identity-gate"><p>${status.configured?'Sign in with the verified adult account that owns this circle.':'Sign in with Microsoft before claiming this adult-owned board.'}</p><button id="entra-sign-in" class="primary" type="button">Sign in with Microsoft</button><small>Identity is handled only by ${escapeHtml(new URL(authority).hostname)}, the Sociobot Microsoft Entra External ID tenant.</small></div>`}
      <p class="privacy-note"><span aria-hidden="true">⌁</span> Private by default · No ads · Learner aliases welcome</p>
    </section>
    <figure class="gate-art"><picture><source type="image/webp" srcset="/art/lantern-room-768.webp 768w, /art/lantern-room-1536.webp 1536w" sizes="(max-width: 900px) 100vw, 56vw"><img src="/art/lantern-room-1536.webp" width="1536" height="1024" alt="An empty, blue-hour mathematics workshop with problem cards glowing beneath a desk lamp" fetchpriority="high" decoding="async"></picture><figcaption>Every attempt leaves a trail.</figcaption></figure>
  </main><footer class="public-footer"><a href="/privacy">Privacy</a><a href="/terms">Terms</a><span>Original AI-assisted environmental art</span></footer>`;
  document.querySelector('#entra-sign-in')?.addEventListener('click',()=>signIn());
  document.querySelector<HTMLFormElement>('#gate-form')?.addEventListener('submit',async e=>{
    e.preventDefault();const formElement=e.currentTarget as HTMLFormElement;const form=new FormData(formElement);const button=formElement.querySelector<HTMLButtonElement>('button')!;button.disabled=true;button.textContent='Creating…';
    const data:Record<string,unknown>=Object.fromEntries(form);data.adult_confirmed=form.get('adult_confirmed')==='on';
    try{await send('/setup',data);await loadBoard()}catch(err){showFormError(err)}finally{button.disabled=false;button.textContent='Create private board'}
  });
}

async function loadBoard(){
  try{board=await api<Board>('/board');rememberBoard();selectBoardDefaults();renderApp()}catch(err){if(!navigator.onLine){if(!restoreOfflineBoard())renderConnectionError();return}if(err instanceof ApiFailure&&(err.status===401||err.status===403))renderGate({configured:true,signed_in:err.status===403,authenticated:false});else renderConnectionError()}
}
function selectBoardDefaults(){if(!board)return;selectedSession=selectedSession&&board.sessions.some(s=>s.id===selectedSession)?selectedSession:board.sessions[0]?.id||0;selectedProblem=selectedProblem&&board.problems.some(p=>p.id===selectedProblem)?selectedProblem:board.problems.find(p=>p.session_id===selectedSession)?.id||0;selectedLearner=selectedLearner&&board.learners.some(l=>l.id===selectedLearner)?selectedLearner:board.learners[0]?.id||0}
function rememberBoard(){if(board)localStorage.setItem(offlineBoardKey,JSON.stringify(board))}
function restoreOfflineBoard(){try{const cached=localStorage.getItem(offlineBoardKey);if(!cached)return false;board=JSON.parse(cached) as Board;online=false;selectBoardDefaults();renderApp();toast('Offline copy open. You can review records and keep drafts on this device.');return true}catch{return false}}

function renderApp(){if(!board)return;setTitle(board.group_name);app.innerHTML=`<div class="shell">
  <header class="topbar"><a class="brand" href="#board" data-view="board"><span class="mark">∴</span><span><small>Math Circle Board</small><strong>${escapeHtml(board.group_name)}</strong></span></a>
    <nav aria-label="Main navigation"><a href="#board" data-view="board" ${view==='board'?'aria-current="page"':''}>Board</a><a href="#learners" data-view="learners" ${view==='learners'?'aria-current="page"':''}>Learners</a><a href="#plus" data-view="plus" ${view==='plus'?'aria-current="page"':''}>${plusUnlocked?'Plus ✓':'Plus'}</a><a href="#settings" data-view="settings" aria-label="Settings" ${view==='settings'?'aria-current="page"':''}>Settings</a></nav>
  </header>
  <main id="main" class="workspace"><h1 class="sr-only">${escapeHtml(board.group_name)} facilitator board</h1>${renderView()}</main>
  <div id="notice" class="notice" aria-live="polite"></div>
  <footer class="app-footer"><span>Your circle’s records stay on this server.</span><span><a href="/privacy">Privacy</a> · <a href="/terms">Terms</a> · Original AI-assisted art</span></footer>
  ${online?'':'<div class="offline" role="status">You’re offline. Your writing stays in this browser; reconnect before saving.</div>'}
  </div>`;bindCommon();bindView();loadPrivateImages();renderNotice()}

function renderView(){switch(view){case'learners':return renderLearners();case'recap':return renderRecap();case'plus':return renderPlus();case'settings':return renderSettings();default:return renderBoard()}}
function session():CircleSession|undefined{return board?.sessions.find(s=>s.id===selectedSession)}
function problem():Problem|undefined{return board?.problems.find(p=>p.id===selectedProblem)}
function learner():Learner|undefined{return board?.learners.find(l=>l.id===selectedLearner)}
function attempt():Attempt|undefined{return board?.attempts.find(a=>a.learner_id===selectedLearner&&a.problem_id===selectedProblem)}

function renderBoard(){if(!board)return'';const current=session();return`<section class="board-head"><div><p class="eyebrow">Session trail</p><h2>${current?escapeHtml(current.title):'Plan the first gathering'}</h2>${current?`<p>${shortDate(current.session_date)}${current.focus?` · ${escapeHtml(current.focus)}`:''}</p>`:'<p>Start with a date and a question worth lingering over.</p>'}</div><div class="head-actions"><label class="select-label">Session<select id="session-select">${board.sessions.map(s=>`<option value="${s.id}" ${s.id===selectedSession?'selected':''}>${escapeHtml(s.title)} · ${shortDate(s.session_date)}</option>`).join('')}</select></label>${current?'<button id="recap-button" class="secondary">Print recap</button>':''}<button id="toggle-session" class="primary">New session</button></div></section>
  <section id="session-form-wrap" class="reveal" hidden><form id="session-form" class="inline-form"><div><h3>New session</h3><p>Give this gathering a clear place in the sequence.</p></div><label>Session title<input name="title" required maxlength="100" placeholder="Invariants in motion"></label><label>Date<input name="session_date" type="date" required value="${today()}"></label><label>Guiding focus<input name="focus" maxlength="300" placeholder="What stays unchanged?"></label><button class="primary" type="submit">Add session</button><p class="form-error" role="alert"></p></form></section>
  ${current?renderSession(current):renderFirstSession()}`}

function renderFirstSession(){return`<section class="empty-state"><div class="empty-orbit" aria-hidden="true">①</div><h2>The table is clear.</h2><p>Create a session, add two or three open problems, then invite learner thinking into the record.</p><button class="primary" data-open-session>Create the first session</button></section>`}
function renderSession(current:CircleSession){if(!board)return'';const problems=board.problems.filter(p=>p.session_id===current.id);return`<section class="trail-section" aria-labelledby="trail-title"><div class="section-title"><div><p class="eyebrow">Problem sequence</p><h3 id="trail-title">The path through this session</h3></div><button id="toggle-problem" class="secondary">Add problem</button></div>
  <div id="problem-form-wrap" class="reveal" hidden><form id="problem-form" class="inline-form problem-form"><label>Short title<input name="title" required maxlength="120" placeholder="The disappearing corners"></label><label>Open prompt<textarea name="prompt" required maxlength="2000" rows="3" placeholder="A rectangle has its corners cut away… What do you notice?"></textarea></label><button class="primary" type="submit">Add to sequence</button><p class="form-error" role="alert"></p></form></div>
  ${problems.length?`<ol class="problem-trail">${problems.map((p,i)=>`<li><button class="problem-card ${p.id===selectedProblem?'selected':''}" data-problem="${p.id}" aria-pressed="${p.id===selectedProblem}"><span class="problem-number">${String(i+1).padStart(2,'0')}</span><span><strong>${escapeHtml(p.title)}</strong><small>${escapeHtml(p.prompt)}</small></span><span class="trail-status">${attemptProgress(p.id)}</span></button></li>`).join('')}</ol>`:`<div class="inline-empty"><span aria-hidden="true">↝</span><p><strong>No problems in the trail yet.</strong><br>Add an open prompt to begin.</p></div>`}
  </section>${problems.length?renderWorkbench():''}`}
function attemptProgress(problemId:number){if(!board)return'';const items=board.attempts.filter(a=>a.problem_id===problemId);return `${items.filter(a=>a.status==='shared').length}/${board.learners.length} shared`}

function renderWorkbench(){if(!board)return'';const p=problem();if(!p)return'';if(!board.learners.length)return`<section class="workbench empty-workbench"><div><p class="eyebrow">Attempt workbench</p><h3>Add a learner to record thinking</h3><p>Aliases or first names are enough. Avoid emails and identifying details.</p></div><button class="primary" data-view="learners">Add learners</button></section>`;const a=attempt();const strategies=a?parseStrategies(a.strategies):[];const attachments=a?board.attachments.filter(x=>x.attempt_id===a.id):[];return`<section class="workbench" aria-labelledby="workbench-title"><div class="workbench-heading"><div><p class="eyebrow">Attempt workbench</p><h3 id="workbench-title">${escapeHtml(p.title)}</h3></div><label class="select-label">Learner<select id="learner-select">${board.learners.map(l=>`<option value="${l.id}" ${l.id===selectedLearner?'selected':''}>${escapeHtml(l.alias)}</option>`).join('')}</select></label></div>
  <p class="problem-prompt">${escapeHtml(p.prompt)}</p><form id="attempt-form" class="attempt-form"><div class="status-row"><span id="status-label">Where are they now?</span>${(['not_started','exploring','shared'] as const).map(s=>`<label class="status-option"><input type="radio" name="status" value="${s}" ${(a?.status||'not_started')===s?'checked':''}><span>${statusLabel(s)}</span></label>`).join('')}</div>
  <label>What they tried<textarea name="thinking" rows="5" maxlength="5000" placeholder="Capture the partial idea, diagram, conjecture, or useful wrong turn…">${escapeHtml(a?.thinking||draftValue('thinking'))}</textarea></label>
  <fieldset class="strategies"><legend>Strategies tried</legend><div id="strategy-chips">${strategies.map(s=>chip(s)).join('')}</div><div class="add-strategy"><label class="sr-only" for="strategy-input">Add a strategy</label><input id="strategy-input" maxlength="40" placeholder="e.g. draw a diagram"><button type="button" id="add-strategy" class="secondary">Add strategy</button></div>${plusUnlocked?`<div class="preset-row" aria-label="Circle Plus strategy palette">${['Try a smaller case','Draw a diagram','Work backwards','Look for an invariant'].map(s=>`<button type="button" class="preset" data-preset="${s}">+ ${s}</button>`).join('')}</div>`:''}</fieldset>
  <label class="private-note"><span><strong>Private facilitator note</strong><small>Never shown in the printable learner recap.</small></span><textarea name="private_note" rows="3" maxlength="3000" placeholder="A prompt to try next time…">${escapeHtml(a?.private_note||draftValue('private_note'))}</textarea></label>
  <div class="save-row"><button class="primary" type="submit">Save attempt</button><span id="save-state" role="status">${a?`Last saved ${new Date(a.updated_at*1000).toLocaleString()}`:'Not saved yet'}</span></div></form>
  <section class="evidence" aria-labelledby="evidence-title"><div><h4 id="evidence-title">Photo evidence</h4><p>Private images of paper work only. JPEG, PNG, or WebP under 5 MB.</p></div>${a?`<label class="upload-button">Add photo<input id="photo-input" type="file" accept="image/jpeg,image/png,image/webp"></label>`:'<small>Save the attempt before adding a photo.</small>'}<div class="photo-grid">${attachments.map(x=>`<figure><img data-private-image="${x.id}" alt="Uploaded attempt: ${escapeHtml(x.original_name)}" loading="lazy" width="220" height="160"><figcaption>${escapeHtml(x.original_name)} <button class="text-danger" data-delete-file="${x.id}">Remove</button></figcaption></figure>`).join('')}</div></section>
  </section>`}
function chip(value:string){return`<span class="chip" data-value="${escapeHtml(value)}">${escapeHtml(value)}<button type="button" aria-label="Remove strategy ${escapeHtml(value)}">×</button></span>`}
function draftKey(){return`mcb-draft:${selectedLearner}:${selectedProblem}`}
function draftValue(key:string){try{return JSON.parse(localStorage.getItem(draftKey())||'{}')[key]||''}catch{return''}}

function renderLearners(){if(!board)return'';return`<section class="page-section narrow"><div class="board-head"><div><p class="eyebrow">Private roster</p><h2>Learners</h2><p>Use a first name or alias. No email address is needed.</p></div><span class="count">${board.learners.length} learner${board.learners.length===1?'':'s'}</span></div><form id="learner-form" class="add-learner"><label>Learner alias<input name="alias" required maxlength="60" placeholder="Ada"></label><button class="primary" type="submit">Add learner</button><p class="form-error" role="alert"></p></form>${board.learners.length?`<ul class="learner-list">${board.learners.map(l=>`<li><span class="avatar" aria-hidden="true">${escapeHtml(l.alias[0]?.toUpperCase()||'?')}</span><span><strong>${escapeHtml(l.alias)}</strong><small>${board!.attempts.filter(a=>a.learner_id===l.id).length} recorded attempts</small></span><button class="text-danger" data-delete-learner="${l.id}" data-name="${escapeHtml(l.alias)}">Remove</button></li>`).join('')}</ul>`:`<div class="empty-state compact"><h3>No learner records yet</h3><p>Add aliases when you are ready to capture attempts.</p></div>`}</section>`}

function renderRecap(){if(!board)return'';const s=session();if(!s)return'';const problems=board.problems.filter(p=>p.session_id===s.id);return`<section class="recap"><div class="no-print recap-toolbar"><button class="secondary" data-view="board">← Back to board</button><div><button id="print" class="primary">Print one-page recap</button></div></div><header class="recap-title"><p>Math Circle Board · Session recap</p><h2>${escapeHtml(board.group_name)}</h2><div><strong>${escapeHtml(s.title)}</strong><span>${shortDate(s.session_date)}</span></div>${s.focus?`<p>Focus: ${escapeHtml(s.focus)}</p>`:''}</header>
  <section class="recap-summary"><div><span>${board.learners.length}</span> learners</div><div><span>${problems.length}</span> problems</div><div><span>${board.attempts.filter(a=>problems.some(p=>p.id===a.problem_id)&&a.status==='shared').length}</span> shared attempts</div></section>
  ${board.learners.map(l=>{const records=board!.attempts.filter(a=>a.learner_id===l.id&&problems.some(p=>p.id===a.problem_id)&&a.status!=='not_started');return`<section class="learner-recap"><h3>${escapeHtml(l.alias)}</h3>${records.length?`<ul>${records.map(a=>{const p=board!.problems.find(x=>x.id===a.problem_id)!;return`<li><div><strong>${escapeHtml(p.title)}</strong><span>${statusLabel(a.status)}</span></div>${a.thinking?`<p>${escapeHtml(a.thinking)}</p>`:''}${parseStrategies(a.strategies).length?`<small>Strategies: ${parseStrategies(a.strategies).map(escapeHtml).join(' · ')}</small>`:''}</li>`}).join('')}</ul>`:'<p class="muted">No attempt recorded this session.</p>'}</section>`}).join('')}<footer class="recap-footer">Private facilitator-generated record · ${new Date().toLocaleDateString()}</footer></section>`}

function renderPlus(){return`<section class="page-section plus-page"><div class="plus-hero"><p class="eyebrow">Circle Plus</p><h2>${plusUnlocked?'Your lantern is lit.':'Keep volunteer circles free. Equip growing clubs.'}</h2><p>${plusUnlocked?'Reusable strategy prompts are available in every attempt workbench.':'A one-time license adds a reusable strategy palette now and future organization controls, while every core learning record stays free.'}</p><div class="price"><strong>$39</strong><span>one-time purchase</span></div>${plusUnlocked?'<p class="success">✓ License active on this device</p>':`<a class="primary button-link" href="${billing}/products/${slug}/checkout">Buy Circle Plus</a>`}</div><div class="plus-details"><h3>What Plus unlocks</h3><ul><li><span>↝</span><div><strong>Strategy palette</strong><p>Add proven prompts—smaller cases, diagrams, invariants—with one tap.</p></div></li><li><span>⌁</span><div><strong>Growing-club tools</strong><p>Future organization controls and expanded storage are included with this license.</p></div></li></ul><h3>Restore a purchase</h3><form id="license-form"><label>License token<input name="license" autocomplete="off" required placeholder="Paste your license token"></label><button class="secondary" type="submit">Verify license</button><p class="form-error" role="alert"></p></form><p class="fineprint">Secure checkout is hosted by Sociobot. Dodo is merchant of record; refunds there revoke the license automatically. See <a href="/privacy">privacy</a> and <a href="/terms">terms</a>.</p></div></section>`}

function renderSettings(){if(!board)return'';return`<section class="page-section narrow"><p class="eyebrow">Stewardship</p><h2>Settings & data</h2><div class="settings-list"><section><div><h3>Export everything</h3><p>Download learner aliases, sessions, problems, attempts, private notes, and photo files as JSON.</p></div><button id="export-data" class="secondary">Export data</button></section><section><div><h3>End this visit</h3><p>Sign out of Microsoft Entra on this device. Your circle records remain here.</p></div><button id="logout" class="secondary">Sign out</button></section></div><section class="danger-zone"><h3>Session cleanup</h3><p>Delete a whole session and its attempts. This cannot be undone.</p>${board.sessions.map(s=>`<div><span>${escapeHtml(s.title)} · ${shortDate(s.session_date)}</span><button class="text-danger" data-delete-session="${s.id}" data-name="${escapeHtml(s.title)}">Delete session</button></div>`).join('')||'<p>No sessions to delete.</p>'}</section></section>`}

function bindCommon(){document.querySelectorAll<HTMLElement>('[data-view]').forEach(el=>el.addEventListener('click',e=>{e.preventDefault();view=el.dataset.view as typeof view;renderApp()}));window.ononline=()=>{online=true;toast('Back online. You can save again.');renderApp()};window.onoffline=()=>{online=false;renderApp()}}
function bindView(){if(view==='board')bindBoard();if(view==='learners')bindLearners();if(view==='recap')document.querySelector('#print')?.addEventListener('click',()=>window.print());if(view==='plus')bindPlus();if(view==='settings')bindSettings()}
function toggle(id:string,show?:boolean){const el=document.querySelector<HTMLElement>(id);if(el){el.hidden=show===undefined?!el.hidden:!show;if(!el.hidden)el.querySelector<HTMLElement>('input,textarea')?.focus()}}
function bindBoard(){
  document.querySelector('#toggle-session')?.addEventListener('click',()=>toggle('#session-form-wrap'));document.querySelector('[data-open-session]')?.addEventListener('click',()=>toggle('#session-form-wrap',true));document.querySelector('#toggle-problem')?.addEventListener('click',()=>toggle('#problem-form-wrap'));
  document.querySelector<HTMLSelectElement>('#session-select')?.addEventListener('change',e=>{selectedSession=Number((e.currentTarget as HTMLSelectElement).value);selectedProblem=board?.problems.find(p=>p.session_id===selectedSession)?.id||0;renderApp()});document.querySelectorAll<HTMLElement>('[data-problem]').forEach(x=>x.addEventListener('click',()=>{selectedProblem=Number(x.dataset.problem);renderApp()}));document.querySelector<HTMLSelectElement>('#learner-select')?.addEventListener('change',e=>{selectedLearner=Number((e.currentTarget as HTMLSelectElement).value);renderApp()});document.querySelector('#recap-button')?.addEventListener('click',()=>{view='recap';renderApp()});
  bindJsonForm('#session-form','/sessions',()=>loadBoard());bindJsonForm('#problem-form','/problems',()=>loadBoard(),()=>({session_id:selectedSession}));
  const form=document.querySelector<HTMLFormElement>('#attempt-form');if(form){const saveDraft=()=>{const fd=new FormData(form);localStorage.setItem(draftKey(),JSON.stringify({thinking:fd.get('thinking'),private_note:fd.get('private_note')}))};form.querySelectorAll('textarea').forEach(t=>t.addEventListener('input',saveDraft));form.addEventListener('submit',saveAttempt);document.querySelector('#add-strategy')?.addEventListener('click',()=>addStrategy());document.querySelector('#strategy-input')?.addEventListener('keydown',e=>{if((e as KeyboardEvent).key==='Enter'){e.preventDefault();addStrategy()}});document.querySelectorAll<HTMLElement>('[data-preset]').forEach(x=>x.addEventListener('click',()=>addStrategy(x.dataset.preset)));bindChipRemoval()}
  document.querySelector<HTMLInputElement>('#photo-input')?.addEventListener('change',uploadPhoto);document.querySelectorAll<HTMLElement>('[data-delete-file]').forEach(x=>x.addEventListener('click',()=>deletePhoto(Number(x.dataset.deleteFile))));
}
function bindJsonForm(selector:string,path:string,done:()=>void,extra=()=>({})){const form=document.querySelector<HTMLFormElement>(selector);form?.addEventListener('submit',async e=>{e.preventDefault();const button=form.querySelector<HTMLButtonElement>('button[type=submit]')!;button.disabled=true;try{await send(path,{...Object.fromEntries(new FormData(form)),...extra()});toast('Saved to the board.');done()}catch(err){showFormError(err,form)}finally{button.disabled=false}})}
function strategies(){return [...document.querySelectorAll<HTMLElement>('#strategy-chips .chip')].map(x=>x.dataset.value||'')}
function addStrategy(preset?:string){const input=document.querySelector<HTMLInputElement>('#strategy-input')!;const value=(preset||input.value).trim();if(!value||strategies().some(s=>s.toLowerCase()===value.toLowerCase()))return;const wrap=document.querySelector('#strategy-chips')!;wrap.insertAdjacentHTML('beforeend',chip(value));input.value='';bindChipRemoval();input.focus()}
function bindChipRemoval(){document.querySelectorAll<HTMLButtonElement>('.chip button').forEach(b=>{b.onclick=()=>b.parentElement?.remove()})}
async function saveAttempt(e:SubmitEvent){e.preventDefault();if(!online){toast('You’re offline. Draft kept on this device.');return}const form=e.currentTarget as HTMLFormElement;const button=form.querySelector<HTMLButtonElement>('button[type=submit]')!;button.disabled=true;document.querySelector('#save-state')!.textContent='Saving…';try{await send('/attempts',{...Object.fromEntries(new FormData(form)),learner_id:selectedLearner,problem_id:selectedProblem,strategies:strategies()});localStorage.removeItem(draftKey());toast('Attempt saved.');await loadBoard()}catch(err){document.querySelector('#save-state')!.textContent=messageOf(err)}finally{button.disabled=false}}
async function uploadPhoto(e:Event){const input=e.currentTarget as HTMLInputElement;const file=input.files?.[0],a=attempt();if(!file||!a)return;const data=new FormData();data.append('image',file);try{await api(`/attempts/${a.id}/upload`,{method:'POST',body:data});toast('Photo added privately.');await loadBoard()}catch(err){toast(messageOf(err))}}
async function deletePhoto(id:number){if(!confirm('Remove this attempt photo? This cannot be undone.'))return;try{await api(`/files/${id}`,{method:'DELETE'});toast('Photo removed.');await loadBoard()}catch(err){toast(messageOf(err))}}
async function loadPrivateImages(){for(const image of document.querySelectorAll<HTMLImageElement>('[data-private-image]')){try{const blob=await apiBlob(`/files/${image.dataset.privateImage}`);const url=URL.createObjectURL(blob);image.src=url;image.addEventListener('load',()=>URL.revokeObjectURL(url),{once:true})}catch{image.alt='Private attempt image unavailable'}}}
async function exportData(){try{const blob=await apiBlob('/export');const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download='math-circle-board-export.json';link.click();URL.revokeObjectURL(url);toast('Export downloaded.')}catch(err){toast(messageOf(err))}}
function bindLearners(){bindJsonForm('#learner-form','/learners',()=>loadBoard());document.querySelectorAll<HTMLElement>('[data-delete-learner]').forEach(x=>x.addEventListener('click',async()=>{if(!confirm(`Remove ${x.dataset.name} and all of their attempts? This cannot be undone.`))return;try{await api(`/learners/${x.dataset.deleteLearner}`,{method:'DELETE'});toast('Learner record removed.');await loadBoard()}catch(err){toast(messageOf(err))}}))}
function bindPlus(){document.querySelector<HTMLFormElement>('#license-form')?.addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget as HTMLFormElement;const token=String(new FormData(form).get('license')||'').trim();localStorage.setItem(licenseKey,token);localStorage.removeItem(`${licenseKey}:verdict`);await verifyLicense();if(plusUnlocked){toast('Circle Plus unlocked.');renderApp()}else showFormError(new Error('That license could not be verified.'),form)})}
function bindSettings(){document.querySelector('#export-data')?.addEventListener('click',exportData);document.querySelector('#logout')?.addEventListener('click',async()=>{board=null;localStorage.removeItem(offlineBoardKey);await signOut()});document.querySelectorAll<HTMLElement>('[data-delete-session]').forEach(x=>x.addEventListener('click',async()=>{if(!confirm(`Delete “${x.dataset.name}” and every attempt in it? This cannot be undone.`))return;try{await api(`/sessions/${x.dataset.deleteSession}`,{method:'DELETE'});selectedSession=0;toast('Session deleted.');await loadBoard()}catch(err){toast(messageOf(err))}}))}
function showFormError(error:unknown,form:ParentNode=document){const el=form.querySelector<HTMLElement>('.form-error');if(el)el.textContent=messageOf(error)}
function messageOf(error:unknown){return error instanceof Error?error.message:'Something went wrong. Try again.'}

function renderConnectionError(){setTitle('Connection problem');app.innerHTML=`<main id="main" class="connection-error"><div class="mark">∴</div><h1>The board room is out of reach.</h1><p>The server may still be starting. Check your connection, then try again.</p><button class="primary" onclick="location.reload()">Try again</button></main>`}
function renderLegal(path:string){const privacy=path==='/privacy';setTitle(privacy?'Privacy':'Terms');app.innerHTML=`<header class="legal-head"><a class="wordmark" href="/"><span class="mark">∴</span> Math Circle Board</a></header><main id="main" class="legal"><p class="eyebrow">Plain-language ${privacy?'privacy':'terms'}</p><h1>${privacy?'A small record, kept private.':'Terms of use'}</h1>${privacy?`<p>Math Circle Board stores the information an adult facilitator enters: a facilitator name, circle name, learner aliases, session plans, attempt notes, strategy tags, and uploaded images. It does not require learner emails, run ads, or build behavioral profiles. Microsoft Entra External ID handles the adult account; the board stores its stable account identifier, not a password.</p><h2>Where data lives</h2><p>Board data and private images live in this product’s server database. To support an offline reload, the most recently opened board and unsaved text drafts may also live in this browser until the facilitator signs out. Entra’s sign-in state stays in session storage. A license token and cached license verdict may live locally too. License verification sends only the license token to Sociobot’s billing API.</p><h2>Your controls</h2><p>Facilitators can export board data and photo files, remove individual photos and learner records, and delete sessions. Use pseudonyms and avoid unnecessary identifying details. Server operators may retain backups for operational recovery.</p><h2>Payments</h2><p>Sociobot and Dodo, its merchant of record, process Circle Plus checkout. This app never receives card details.</p>`:`<p>Math Circle Board is a lightweight record-keeping tool for adult-run enrichment groups. The adult facilitator is responsible for consent, appropriate use, and avoiding unnecessary personal information about minors.</p><h2>Acceptable use</h2><p>Do not use the service for high-stakes grading, emergency records, illegal material, public child profiles, or content that infringes another person’s rights. Protect access to your Microsoft account.</p><h2>Circle Plus</h2><p>Circle Plus is a $39 one-time license for the features described at purchase. Checkout is provided by Sociobot with Dodo as merchant of record. Refunds are handled there and revoke the related license.</p><h2>Service limits</h2><p>The service is provided as-is without a guarantee of uninterrupted availability. Export important records regularly. Liability is limited to the amount paid for the service where law allows.</p>`}<p class="legal-date">Effective 28 August 2026 · Contact the operator through sociobot.in for privacy or support requests.</p><a class="secondary button-link" href="/">Return to the board</a></main>`}

boot();
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('/sw.js').catch(()=>{}));
